//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juegos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Juegos()
        {
            this.Reseñas = new HashSet<Reseñas>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Genero { get; set; }
        public string Desarrollador { get; set; }
        public Nullable<int> AnioLanzamiento { get; set; }
        public string Plataforma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reseñas> Reseñas { get; set; }
    }
}
