//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reseñas
    {
        public int Id { get; set; }
        public int JuegoId { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> Puntaje { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
